spring:

  datasource:

      username: root

      password: root

      url: jdbc:mysql://${DB_HOST:localhost}:3306/customerdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

  jpa:

      hibernate:

        ddl-auto: update

      show-sql: true

      properties:

        hibernate:

          dialect: org.hibernate.dialect.MySQLDialect

  jackson:

    serialization:

      fail-on-empty-beans: false
  eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 

server:

  port: 0

  error:

    include-message: always
